.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-asset-remove-iso 1  "iso " 
.SH NAME
start\-registry\-os\-asset\-remove\-iso \- Remove ISO file from registry
.SH SYNOPSIS
\fBstart\-registry os asset remove iso\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fIPLATFORM\fR> 
.SH DESCRIPTION
Remove ISO file from registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
.TP
<\fIPLATFORM\fR>
Target platform identifier
