.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-acme-check-challenge 1  "check-challenge " 
.SH NAME
start\-cli\-net\-acme\-check\-challenge \- Check if the port a certificate authority validates on is reachable
.SH SYNOPSIS
\fBstart\-cli net acme check\-challenge\fR <\fB\-\-acme\fR> [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFQDN\fR> <\fIGATEWAY\fR> 
.SH DESCRIPTION
Check if the port a certificate authority validates on is reachable
.SH OPTIONS
.TP
\fB\-\-acme\fR \fI<ACME>\fR
ACME provider identifier or url
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFQDN\fR>
Fully qualified domain name
.TP
<\fIGATEWAY\fR>
Gateway identifier
