.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-info-set-description 1  "set-description "
.SH NAME
start\-cli\-registry\-info\-set\-description \- Set the registry description
.SH SYNOPSIS
\fBstart\-cli registry info set\-description\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIDESCRIPTION\fR>
.SH DESCRIPTION
Set the registry description
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIDESCRIPTION\fR>
Description of the registry, as markdown
