.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-init-package 1  "init-package " 
.SH NAME
start\-cli\-s9pk\-init\-package \- Scaffold a new package from the workspace template
.SH SYNOPSIS
\fBstart\-cli s9pk init\-package\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Scaffold a new package from the workspace template
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Human\-readable package name (e.g. "Hello World")
