.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-tunnel-update 1  "update " 
.SH NAME
start\-cli\-net\-tunnel\-update \- Replace a gateway\*(Aqs WireGuard config in place, keeping its identity
.SH SYNOPSIS
\fBstart\-cli net tunnel update\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fICONFIG\fR> 
.SH DESCRIPTION
Replace a gateway\*(Aqs WireGuard config in place, keeping its identity
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Gateway identifier
.TP
<\fICONFIG\fR>
WireGuard configuration
