.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-unset-secure 1  "unset-secure "
.SH NAME
start\-cli\-net\-gateway\-unset\-secure \- Let StartOS decide whether a gateway\*(Aqs network is trusted with unencrypted traffic
.SH SYNOPSIS
\fBstart\-cli net gateway unset\-secure\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR>
.SH DESCRIPTION
Let StartOS decide whether a gateway\*(Aqs network is trusted with unencrypted traffic
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
