.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-check-port-v6 1  "check-port-v6 " 
.SH NAME
start\-cli\-net\-gateway\-check\-port\-v6 \- Check if a port is reachable over IPv6 (GUA firewall)
.SH SYNOPSIS
\fBstart\-cli net gateway check\-port\-v6\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPORT\fR> <\fIGATEWAY\fR> 
.SH DESCRIPTION
Check if a port is reachable over IPv6 (GUA firewall)
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPORT\fR>
Port number
.TP
<\fIGATEWAY\fR>
Gateway identifier
