.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-http-redirect-set-enabled 1  "set-enabled " 
.SH NAME
start\-cli\-tunnel\-http\-redirect\-set\-enabled \- Turn the port\-80 HTTP→HTTPS redirect on or off for a public IPv4
.SH SYNOPSIS
\fBstart\-cli tunnel http\-redirect set\-enabled\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIP\fR> 
.SH DESCRIPTION
Turn the port\-80 HTTP→HTTPS redirect on or off for a public IPv4
.SH OPTIONS
.TP
\fB\-\-enabled\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIP\fR>
The public IPv4 whose default\-on port\-80 HTTP→HTTPS redirect to toggle
