.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-epp 1  "epp "
.SH NAME
start\-cli\-server\-epp \- Show CPU energy performance preferences
.SH SYNOPSIS
\fBstart\-cli server epp\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fISET\fR]
.SH DESCRIPTION
Show CPU energy performance preferences
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fISET\fR]
CPU energy performance preference
