.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-asset-remove-img 1  "img " 
.SH NAME
start\-cli\-registry\-os\-asset\-remove\-img \- Remove IMG file from registry
.SH SYNOPSIS
\fBstart\-cli registry os asset remove img\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fIPLATFORM\fR> 
.SH DESCRIPTION
Remove IMG file from registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
.TP
<\fIPLATFORM\fR>
Target platform identifier
