.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-init-workspace 1  "init-workspace " 
.SH NAME
start\-cli\-s9pk\-init\-workspace \- Initialize a StartOS packaging workspace
.SH SYNOPSIS
\fBstart\-cli s9pk init\-workspace\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Initialize a StartOS packaging workspace
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR]
Workspace directory to create or initialize (default: current directory)
