.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-pinhole-remove 1  "remove " 
.SH NAME
start\-cli\-tunnel\-pinhole\-remove \- Remove IPv6 pinhole
.SH SYNOPSIS
\fBstart\-cli tunnel pinhole remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGUA\fR> <\fIEXTERNAL_PORT\fR> 
.SH DESCRIPTION
Remove IPv6 pinhole
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGUA\fR>

.TP
<\fIEXTERNAL_PORT\fR>

