.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-set-secure 1  "set-secure " 
.SH NAME
start\-cli\-net\-gateway\-set\-secure \- Mark a gateway\*(Aqs network as trusted, so services\*(Aq non\-SSL addresses are offered on it
.SH SYNOPSIS
\fBstart\-cli net gateway set\-secure\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR> [\fISECURE\fR] 
.SH DESCRIPTION
Mark a gateway\*(Aqs network as trusted, so services\*(Aq non\-SSL addresses are offered on it
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
.TP
[\fISECURE\fR]
Whether the network reached through this gateway is trusted with unencrypted traffic
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
true
.IP \(bu 2
false
.RE
