.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-trust-ca 1  "trust-ca "
.SH NAME
start\-cli\-server\-trust\-ca \- Trust a custom CA root for StartOS host processes
.SH SYNOPSIS
\fBstart\-cli server trust\-ca\fR <\fB\-\-cert\fR> [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Trust a custom CA root for StartOS host processes
.SH OPTIONS
.TP
\fB\-\-cert\fR \fI<CERT>\fR
PEM\-encoded CA certificate
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
