.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-pinhole 1  "pinhole " 
.SH NAME
start\-cli\-tunnel\-pinhole \- Commands for managing IPv6 pinholes
.SH SYNOPSIS
\fBstart\-cli tunnel pinhole\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for managing IPv6 pinholes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-tunnel\-pinhole\-add(1)
Add a new IPv6 pinhole
.TP
start\-cli\-tunnel\-pinhole\-remove(1)
Remove IPv6 pinhole
.TP
start\-cli\-tunnel\-pinhole\-set\-enabled(1)
Enable or disable an IPv6 pinhole
.TP
start\-cli\-tunnel\-pinhole\-update\-label(1)
Update the label of an IPv6 pinhole
