.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-target-delete-legacy 1  "delete-legacy " 
.SH NAME
start\-cli\-backup\-target\-delete\-legacy \- Delete the legacy (V1) backup from a backup target
.SH SYNOPSIS
\fBstart\-cli backup target delete\-legacy\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITARGET_ID\fR> 
.SH DESCRIPTION
Delete the legacy (V1) backup from a backup target
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITARGET_ID\fR>
Backup target identifier
