// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddPinholeParams = {
  /**
   * The client's global IPv6 (GUA) to expose. Must be an address this tunnel
   * delegates to a client — its subnet needs an IPv6 prefix.
   */
  gua: string
  /**
   * External port opened on the GUA.
   */
  externalPort: number
  /**
   * Destination port on the GUA. Omit for a pure pinhole (no NAT, internal ==
   * external); set a different value for a port remap (e.g. 80 -> 443).
   */
  internalPort?: number
  label: string | null
  /**
   * Number of contiguous ports, counting up from external/internal. Default 1.
   */
  count?: number
}
