// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapabilityVerdict = {
  /**
   * `None` = never probed.
   */
  supported: boolean | null
  at: string | null
}
