// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-IPv4 HTTP→HTTPS redirect state. The tunnel runs a redirect on port 80 of
 * every public IPv4 by default; this records the addresses where the user has
 * turned it off (absence = on). The redirect also yields to any port-forward
 * occupying port 80 on that IP, so the two never fight over the port.
 */
export type HttpRedirects = { disabled: string[] }
