// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpRedirectStatus = {
  ip: string
  /**
   * Whether the redirect is on for this IP (default true).
   */
  enabled: boolean
  /**
   * Whether a port-forward already occupies port 80 on this IP, in which case
   * the redirect yields and does not bind.
   */
  forwarded: boolean
}
