// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityVerdict } from './CapabilityVerdict'
import type { GatewayPortMapCapabilities } from './GatewayPortMapCapabilities'
import type { GatewayType } from './GatewayType'
import type { IpInfo } from './IpInfo'

export type NetworkInterfaceInfo = {
  name: string | null
  secure: boolean | null
  ipInfo: IpInfo | null
  type: GatewayType
  portMap: GatewayPortMapCapabilities
  /**
   * The gateway's resolver accepted our last RFC 2136 DNS UPDATE — evidence
   * from the update client (`net::dns_update`). A WireGuard gateway only
   * serves the injected `<hostname>.local` while this is `supported`, so
   * only then is the name listed on it.
   */
  dnsUpdate: CapabilityVerdict
}
