// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One IPv6 GUA firewall entry, keyed by the exposed `[GUA]:external_port`. The
 * destination is always the same GUA. When `internal_port` is `None` (or equals
 * the key's port) it's a pure firewall pinhole — `ct state new accept`, no NAT.
 * When it differs it's a port-only DNAT to `[GUA]:internal_port` (e.g. 80→443),
 * the v6 analogue of a `PortForward::Dnat`.
 */
export type Pinhole = {
  label: string | null
  enabled: boolean
  /**
   * Contiguous ports opened, counting up from the key's port; `1` for single.
   */
  count: number
  /**
   * Destination port on the GUA; `None` means "same as the external (key) port"
   * — a pure pinhole. A different value makes this a port-DNAT.
   */
  internalPort: number | null
  /**
   * Gateway-created (PCP) vs user-added. Drives the UI Manual/Automatic split.
   */
  auto: boolean
}
