// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SniRoute } from './SniRoute'

/**
 * One external-port forward: an nftables DNAT or an SNI-demultiplexed shared
 * port. Mutually exclusive for a given external address.
 */
export type PortForward =
  | {
      kind: 'dnat'
      target: string
      label: string | null
      enabled: boolean
      /**
       * Contiguous ports forwarded (a PCP PORT_SET range); `1` for single-port.
       */
      count: number
      /**
       * Gateway-created (PCP/UPnP) vs user-added. Drives the UI Manual/Automatic split.
       */
      auto: boolean
    }
  | {
      kind: 'sni'
      /**
       * hostname (lowercase; may be `*.suffix`) -> route.
       */
      routes: { [key: string]: SniRoute }
      /**
       * Hostname-less catch-all for this shared external port. Traffic whose
       * SNI matches no `routes` entry — or that carries no SNI (bare-IP TLS,
       * non-TLS) — is spliced here instead of being dropped. `None` closes the
       * port to unmatched traffic. This lets a bare public IP and named
       * domains share one external port, the bare IP acting as the fallback.
       */
      fallback: SniRoute | null
    }
