// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePinholeLabelParams = {
  gua: string
  externalPort: number
  label: string | null
}
