//! Descriptive-label fallback for devices that never advertise a hostname.
//!
//! Some clients deliberately withhold their name from every source
//! `devices::list` consults: ChromeOS never sends DHCP option 12 (a privacy
//! decision — only enterprise-enrolled devices with the `DeviceHostnameTemplate`
//! policy do) and doesn't answer reverse-mDNS with a friendly name; stripped-down
//! IoT DHCP clients behave the same. Rather than jump straight to the opaque
//! `device-<mac>` placeholder, this module derives a descriptive label from what
//! the device *can't* help revealing:
//!
//! 1. **DHCP fingerprint → OS family** ("Windows device"). The option-55
//!    parameter-request order and option-60 vendor class are characteristic of
//!    the OS's DHCP client and ride the request itself, so they survive MAC
//!    randomization. Captured by a dnsmasq `dhcp-script` hook (see
//!    [`FINGERPRINT_SCRIPT`]), persisted per-MAC in the `device_names` cache.
//! 2. **MAC OUI → NIC vendor** ("Apple device"). Always available on Ethernet
//!    (burned-in MACs), absent for randomized WiFi MACs. The fingerprint
//!    outranks the OUI because it identifies the machine rather than the
//!    network interface — a USB Ethernet dongle's OUI says "TP-Link" even when
//!    the laptop behind it is a Mac.
//!
//! Labels are derived, not learned, so they are recomputed every poll and never
//! written to the `device_names` cache as names — a later real hostname or a
//! refreshed table wins automatically. (The raw *fingerprint* is cached, so a
//! device keeps its OS label across reboots without waiting for a DHCP renewal.)
//!
//! Labels are English-only, matching the existing `"VPN Device"` convention in
//! `devices.rs`.
//!
//! # Live validation (bench)
//!
//! The fingerprint table below is seeded from widely-documented signatures, not
//! bench captures. To validate and extend it, connect each client OS to a bench
//! router and read `/var/run/dnsmasq/dhcp.fingerprints` (force a fresh DHCP
//! exchange by reconnecting): the line is `MAC|option-55 list|vendor class`.
//! Worth capturing: Windows 10/11, macOS, iOS, Android, Debian (dhclient and
//! systemd-networkd), and above all **ChromeOS** — the client this feature
//! exists for. It is undocumented whether ChromeOS emits a distinguishable
//! vendor class (its shill/dhcpcd lineage suggests it may land on the generic
//! "Linux" rule); the bench capture decides whether it earns a dedicated
//! "ChromeOS" rule or falls through to the OUI rung. Devices with burned-in
//! Ethernet MACs are covered by the OUI rung regardless; devices using WiFi MAC
//! randomization are covered only by the fingerprint rung.

use std::collections::HashMap;
use std::io::Read;
use std::path::Path;
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};
use uciedit::{dump_all, parse_all, Arena, TypedSection};

use crate::prelude::*;

/// IEEE MAC-prefix registry snapshot (MA-L + MA-M + MA-S), generated by
/// `projects/start-wrt/build/gen-oui-table.sh` — see that script for
/// provenance, name-cleaning rules, and refresh instructions. Gzipped TSV,
/// one `HEXPREFIX<TAB>VENDOR` line per assignment; the prefix length encodes
/// the registry: 6 nibbles = MA-L (24-bit), 7 = MA-M (28-bit), 9 = MA-S
/// (36-bit).
static OUI_TSV_GZ: &[u8] = include_bytes!("../assets/oui.tsv.gz");

static OUI_TABLE: LazyLock<HashMap<Box<str>, Box<str>>> = LazyLock::new(|| {
    let mut text = String::new();
    match flate2::read::GzDecoder::new(OUI_TSV_GZ).read_to_string(&mut text) {
        Ok(_) => text
            .lines()
            .filter_map(|line| line.split_once('\t'))
            .map(|(prefix, vendor)| (prefix.into(), vendor.into()))
            .collect(),
        Err(e) => {
            // Unreachable short of a corrupted build; degrade to no labels.
            tracing::error!("device_ident: embedded OUI table failed to load: {e}");
            HashMap::new()
        }
    }
});

/// NIC vendor for a MAC, from the embedded IEEE registry snapshot.
///
/// Longest-prefix match (MA-S 36-bit, then MA-M 28-bit, then MA-L 24-bit) —
/// small vendors hold sub-blocks of a parent OUI, and the parent
/// ("IEEE Registration Authority") rows are excluded at generation time so an
/// unmatched sub-block falls through to `None` rather than a meaningless label.
///
/// Returns `None` for locally-administered MACs (the randomized addresses
/// modern phones/laptops use on WiFi — they have no registry entry by
/// construction) and multicast MACs.
pub fn oui_vendor(mac: &str) -> Option<&'static str> {
    let hex: String = mac
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .collect::<String>()
        .to_uppercase();
    if hex.len() != 12 || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    // Bit 0 of the first octet = multicast, bit 1 = locally administered.
    let first = u8::from_str_radix(&hex[..2], 16).ok()?;
    if first & 0x03 != 0 {
        return None;
    }
    let table = LazyLock::force(&OUI_TABLE);
    [9, 7, 6]
        .into_iter()
        .find_map(|len| table.get(&hex[..len]).map(|v| &**v))
}

/// Last 6 hex digits of a MAC, lowercased — the stable per-device suffix shared
/// with `devices::fallback_name`, kept in every derived label so two unnamed
/// devices from the same vendor stay distinguishable.
pub fn mac_suffix(mac: &str) -> String {
    let hex: String = mac.chars().filter(|c| *c != ':').collect();
    let start = hex.len().saturating_sub(6);
    hex[start..].to_lowercase()
}

// ── DHCP fingerprints ──

/// What a device's DHCP request revealed about its OS: the option-55
/// parameter-request list (comma-separated decimals, as dnsmasq reports it)
/// and the option-60 vendor class. Either may be empty, not both.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Fingerprint {
    pub options: String,
    pub vendor_class: String,
}

/// OS family from a DHCP fingerprint, or `None` if unrecognized.
///
/// Vendor class first — it is explicit and version-stable (`MSFT 5.0` has
/// identified every Windows since 2000) — then exact option-55 sequences for
/// the stacks that send no vendor class (Apple's). Rules are deliberately
/// conservative: a miss falls through to the OUI rung, which is harmless,
/// while a wrong match mislabels a device. See the module docs for the bench
/// procedure that validates/extends this table.
pub fn fingerprint_os(fp: &Fingerprint) -> Option<&'static str> {
    let vc = fp.vendor_class.as_str();
    if vc.starts_with("MSFT") {
        return Some("Windows");
    }
    if vc.starts_with("android-dhcp") {
        return Some("Android");
    }
    // dhcpcd (dhcpcd-<ver>:<os>:...) and BusyBox udhcpc (udhcp <ver>) are
    // generic Unix clients: dhcpcd is the default on many distros (and the
    // ancestry of ChromeOS's client); udhcpc ships on embedded/OpenWrt-like
    // devices.
    if vc.starts_with("dhcpcd") || vc.starts_with("udhcp") {
        return Some("Linux");
    }
    match fp.options.as_str() {
        // macOS/iOS request lists (no vendor class): the classic order, and
        // the newer one with option 114 (captive-portal API).
        "1,121,3,6,15,119,252" | "1,121,3,6,15,114,119,252" => Some("Apple"),
        // Canonical Windows 10/11 list — redundant with the MSFT vendor class,
        // but catches clients configured to omit option 60.
        "1,3,6,15,31,33,43,44,46,47,119,121,249,252" => Some("Windows"),
        // NetworkManager's internal client (Ubuntu/Fedora desktop default):
        // sends no vendor class. Bench-captured 2026-08-03 (Ubuntu).
        "1,2,6,12,15,26,28,121,3,33,40,41,42,119,249,252,17" => Some("Linux"),
        _ => None,
    }
}

/// Descriptive display label for an unnamed device, e.g. `Apple device (b2c3d4)`
/// or `Windows device (b2c3d4)`. Fingerprint (OS) outranks OUI (NIC vendor);
/// `None` when neither identifies the device.
pub fn device_label(mac: &str, fingerprint: Option<&Fingerprint>) -> Option<String> {
    let ident = fingerprint
        .and_then(fingerprint_os)
        .or_else(|| oui_vendor(mac))?;
    Some(format!("{} device ({})", ident, mac_suffix(mac)))
}

// ── Fingerprint capture: dnsmasq dhcp-script hook ──

/// Where the hook script lives. Listed in sysupgrade's keep.d (see
/// `build/stage-files.sh`), but the daemon rewrites it at every boot anyway
/// (see [`ensure_dhcp_fingerprint_hook`]), so existing routers converge on
/// the first boot after an OTA update even without the keep entry.
pub const FINGERPRINT_SCRIPT_PATH: &str = "/etc/startwrt/dhcp-fingerprint.sh";

/// Where the hook appends fingerprint lines. dnsmasq runs inside a procd
/// ujail whose only writable paths are `/var/run/dnsmasq/` and the leasefile,
/// so the file must live there — NOT in `/tmp` (silently unwritable from the
/// jail). tmpfs either way: lost on reboot, which is why fingerprints are
/// persisted into the `device_names` cache.
pub const FINGERPRINT_FILE: &str = "/var/run/dnsmasq/dhcp.fingerprints";

/// Compact [`FINGERPRINT_FILE`] once it exceeds this (dedup keeps ~one line
/// per device, so steady state stays far below).
const FINGERPRINT_FILE_MAX: u64 = 64 * 1024;

/// The hook script. Constraints that shape it (verified against the shipped
/// OpenWrt `dnsmasq.init` + `/usr/lib/dnsmasq/dhcp-script.sh`):
/// - The wrapper **sources** it (`. "$USER_DHCPSCRIPT" "$@"`) inside the
///   dnsmasq ujail, so it must never `exit` — that would abort the wrapper
///   before its ubus hotplug notify.
/// - The jail mounts no coreutils, so shell builtins only.
/// - Values are written raw; the daemon-side parser is the validation layer
///   (a hostile vendor class can at worst forge a display label).
const FINGERPRINT_SCRIPT: &str = r#"#!/bin/sh
# Managed by startwrt — rewritten at every boot; edits will be lost.
# Sourced (not executed) by dnsmasq's dhcp-script wrapper inside the dnsmasq
# ujail: no `exit`, builtins only, and /var/run/dnsmasq is the only writable
# directory. Records one line per DHCP add/old event:
#   MAC|option-55 request list|option-60 vendor class
case "$1" in
	add|old)
		if [ -n "$2" ] && [ -n "${DNSMASQ_REQUESTED_OPTIONS}${DNSMASQ_VENDOR_CLASS}" ]; then
			printf '%s|%s|%s\n' "$2" "${DNSMASQ_REQUESTED_OPTIONS:-}" "${DNSMASQ_VENDOR_CLASS:-}" >> /var/run/dnsmasq/dhcp.fingerprints 2>/dev/null
		fi
	;;
esac
"#;

/// Minimal view of a `config dnsmasq` section: `TypedSection::write` only
/// touches declared fields, so setting `dhcpscript` through this struct
/// preserves every other option on the (stock, hand-edited, or
/// profile-created) section.
#[derive(Debug, TypedSection, Default)]
#[uci(ty = "dnsmasq")]
struct DnsmasqScriptCfg {
    #[uci(default)]
    dhcpscript: Option<String>,
}

/// Point every `config dnsmasq` section's `dhcpscript` at the hook script.
/// Returns whether anything changed. Testable half of
/// [`ensure_dhcp_fingerprint_hook`].
pub async fn ensure_uci_dhcpscript(uci_root: impl AsRef<Path>) -> Result<bool, Error> {
    let mut retries = 4;
    loop {
        let arena = Arena::new();
        let mut cfgs = parse_all(uci_root.as_ref(), &arena, &["dhcp"]).await?;
        let mut changed = false;
        for section in &mut cfgs["dhcp"].sections {
            if section.ty() != "dnsmasq" {
                continue;
            }
            let mut cfg = section.get::<DnsmasqScriptCfg>()?;
            if cfg.dhcpscript.as_deref() != Some(FINGERPRINT_SCRIPT_PATH) {
                cfg.dhcpscript = Some(FINGERPRINT_SCRIPT_PATH.to_string());
                section.set(&cfg)?;
                changed = true;
            }
        }
        if !changed {
            return Ok(false);
        }
        match dump_all(uci_root.as_ref(), cfgs).await {
            Ok(()) => return Ok(true),
            Err(uciedit::Error::Conflict { .. }) if retries > 0 => {
                retries -= 1;
                continue;
            }
            Err(e) => return Err(e.into()),
        }
    }
}

/// Boot-time provisioning (idempotent): install the hook script, wire it into
/// every dnsmasq instance via UCI, and reload dnsmasq if anything changed.
/// Daemon-side rather than a `uci-defaults` file so OTA-updated routers get
/// the hook without a fresh flash.
pub async fn ensure_dhcp_fingerprint_hook() -> Result<(), Error> {
    let script_current = tokio::fs::read_to_string(FINGERPRINT_SCRIPT_PATH)
        .await
        .map(|c| c == FINGERPRINT_SCRIPT)
        .unwrap_or(false);
    if !script_current {
        use std::os::unix::fs::PermissionsExt;
        let _ = tokio::fs::create_dir_all("/etc/startwrt").await;
        tokio::fs::write(FINGERPRINT_SCRIPT_PATH, FINGERPRINT_SCRIPT)
            .await
            .map_err(|e| {
                Error::new(
                    eyre!("write {FINGERPRINT_SCRIPT_PATH}: {e}"),
                    ErrorKind::Filesystem,
                )
            })?;
        tokio::fs::set_permissions(
            FINGERPRINT_SCRIPT_PATH,
            std::fs::Permissions::from_mode(0o755),
        )
        .await
        .map_err(|e| {
            Error::new(
                eyre!("chmod {FINGERPRINT_SCRIPT_PATH}: {e}"),
                ErrorKind::Filesystem,
            )
        })?;
    }

    let uci_changed = ensure_uci_dhcpscript("/etc/config").await?;

    if !script_current || uci_changed {
        crate::run_quiet_async(tokio::process::Command::new("/etc/init.d/dnsmasq").arg("reload"))
            .await
            .map_err(|e| Error::new(eyre!("dnsmasq reload: {e}"), ErrorKind::Filesystem))?;
    }
    Ok(())
}

// ── Fingerprint file: parse / load / compact ──

/// Canonical uppercase-colon MAC (the in-memory convention in `devices.rs`),
/// or `None` if the input isn't a MAC.
fn normalize_mac(raw: &str) -> Option<String> {
    let hex: String = raw
        .chars()
        .filter(|c| *c != ':' && *c != '-')
        .collect::<String>()
        .to_uppercase();
    if hex.len() != 12 || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    Some(
        hex.as_bytes()
            .chunks(2)
            .map(|pair| std::str::from_utf8(pair).unwrap())
            .collect::<Vec<_>>()
            .join(":"),
    )
}

/// Parse `MAC|options|vendor class` lines into a per-MAC map, last entry wins
/// (the file is append-only, so last = most recent DHCP event). This is the
/// validation layer for the raw hook output: malformed lines — including any
/// forged via newlines smuggled through a hostile vendor class — are dropped,
/// the options field must look like an option list, and the vendor class is
/// length-capped.
pub fn parse_fingerprint_lines(content: &str) -> HashMap<String, Fingerprint> {
    let mut map = HashMap::new();
    for line in content.lines() {
        let mut parts = line.splitn(3, '|');
        let (Some(mac), Some(options), Some(vendor_class)) =
            (parts.next(), parts.next(), parts.next())
        else {
            continue;
        };
        let Some(mac) = normalize_mac(mac) else {
            continue;
        };
        if options.len() > 256 || !options.bytes().all(|b| b.is_ascii_digit() || b == b',') {
            continue;
        }
        let vendor_class: String = vendor_class.chars().take(128).collect();
        if options.is_empty() && vendor_class.is_empty() {
            continue;
        }
        map.insert(
            mac,
            Fingerprint {
                options: options.to_string(),
                vendor_class,
            },
        );
    }
    map
}

/// Read the live fingerprint file (best-effort: absent file = empty map).
pub async fn load_live_fingerprints() -> HashMap<String, Fingerprint> {
    match tokio::fs::read_to_string(FINGERPRINT_FILE).await {
        Ok(content) => parse_fingerprint_lines(&content),
        Err(_) => HashMap::new(),
    }
}

/// Rewrite the fingerprint file deduped (one line per MAC) once it outgrows
/// [`FINGERPRINT_FILE_MAX`]. Best-effort: a concurrent append from dnsmasq can
/// be lost to the rewrite, which is benign — the event recurs on the next
/// renewal, and the fingerprint is already persisted in the name cache.
pub async fn compact_fingerprint_file() {
    let Ok(meta) = tokio::fs::metadata(FINGERPRINT_FILE).await else {
        return;
    };
    if meta.len() <= FINGERPRINT_FILE_MAX {
        return;
    }
    let Ok(content) = tokio::fs::read_to_string(FINGERPRINT_FILE).await else {
        return;
    };
    let compacted: String = parse_fingerprint_lines(&content)
        .into_iter()
        .map(|(mac, fp)| format!("{}|{}|{}\n", mac, fp.options, fp.vendor_class))
        .collect();
    if let Err(e) = tokio::fs::write(FINGERPRINT_FILE, compacted).await {
        tracing::warn!("device_ident: fingerprint file compaction failed: {e}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_loads_with_all_three_registries() {
        let table = LazyLock::force(&OUI_TABLE);
        assert!(table.len() > 30_000, "table has {} entries", table.len());
        assert!(table.keys().any(|k| k.len() == 6));
        assert!(table.keys().any(|k| k.len() == 7));
        assert!(table.keys().any(|k| k.len() == 9));
    }

    #[test]
    fn ma_l_lookup() {
        assert_eq!(
            oui_vendor("B8:27:EB:12:34:56"),
            Some("Raspberry Pi Foundation")
        );
        // Case- and format-insensitive.
        assert_eq!(oui_vendor("b827eb123456"), Some("Raspberry Pi Foundation"));
    }

    #[test]
    fn ma_s_longest_prefix_wins_and_parent_is_excluded() {
        // 8C1F64AFA is an MA-S assignment; its parent MA-L block 8C1F64 is an
        // "IEEE Registration Authority" row, excluded at generation time.
        assert_eq!(
            oui_vendor("8C:1F:64:AF:A1:23"),
            Some("DATA ELECTRONIC DEVICES")
        );
        // A sub-block of the same parent that isn't assigned (002 as of the
        // 2026-08 snapshot) must yield nothing, not the parent's name.
        assert_eq!(oui_vendor("8C:1F:64:00:20:01"), None);
    }

    #[test]
    fn randomized_and_multicast_macs_have_no_vendor() {
        // 0xDA has the locally-administered bit set (randomized MAC).
        assert_eq!(oui_vendor("DA:27:EB:12:34:56"), None);
        // 01:00:5E is IPv4-multicast space.
        assert_eq!(oui_vendor("01:00:5E:12:34:56"), None);
    }

    #[test]
    fn garbage_macs_are_rejected() {
        assert_eq!(oui_vendor(""), None);
        assert_eq!(oui_vendor("B8:27:EB:12:34"), None);
        assert_eq!(oui_vendor("ZZ:27:EB:12:34:56"), None);
    }

    fn fp(options: &str, vendor_class: &str) -> Fingerprint {
        Fingerprint {
            options: options.into(),
            vendor_class: vendor_class.into(),
        }
    }

    #[test]
    fn fingerprint_vendor_class_rules() {
        assert_eq!(fingerprint_os(&fp("1,3,6", "MSFT 5.0")), Some("Windows"));
        assert_eq!(
            fingerprint_os(&fp("1,3,6", "android-dhcp-14")),
            Some("Android")
        );
        assert_eq!(
            fingerprint_os(&fp("", "dhcpcd-10.0.6:Linux-6.6.0:x86_64:GenuineIntel")),
            Some("Linux")
        );
        assert_eq!(fingerprint_os(&fp("", "udhcp 1.36.1")), Some("Linux"));
    }

    #[test]
    fn fingerprint_option55_rules() {
        assert_eq!(
            fingerprint_os(&fp("1,121,3,6,15,119,252", "")),
            Some("Apple")
        );
        assert_eq!(
            fingerprint_os(&fp("1,121,3,6,15,114,119,252", "")),
            Some("Apple")
        );
        assert_eq!(
            fingerprint_os(&fp("1,3,6,15,31,33,43,44,46,47,119,121,249,252", "")),
            Some("Windows")
        );
        assert_eq!(
            fingerprint_os(&fp(
                "1,2,6,12,15,26,28,121,3,33,40,41,42,119,249,252,17",
                ""
            )),
            Some("Linux")
        );
        // Vendor class outranks the option list.
        assert_eq!(
            fingerprint_os(&fp("1,121,3,6,15,119,252", "MSFT 5.0")),
            Some("Windows")
        );
        assert_eq!(fingerprint_os(&fp("1,3,6,15", "")), None);
    }

    #[test]
    fn label_prefers_fingerprint_over_oui() {
        // Real OUI + Windows fingerprint (the USB-dongle case): OS wins.
        assert_eq!(
            device_label("B8:27:EB:12:34:AB", Some(&fp("1,3,6", "MSFT 5.0"))).as_deref(),
            Some("Windows device (1234ab)")
        );
        // No fingerprint: OUI vendor.
        assert_eq!(
            device_label("B8:27:EB:12:34:AB", None).as_deref(),
            Some("Raspberry Pi Foundation device (1234ab)")
        );
        // Randomized MAC + fingerprint: fingerprint still labels it.
        assert_eq!(
            device_label("DA:27:EB:12:34:56", Some(&fp("1,121,3,6,15,119,252", ""))).as_deref(),
            Some("Apple device (123456)")
        );
        // Neither.
        assert_eq!(device_label("DA:27:EB:12:34:56", None), None);
    }

    #[test]
    fn parse_fingerprint_lines_validates_and_last_wins() {
        let content = "\
aa:bb:cc:dd:ee:01|1,3,6|MSFT 5.0
not a mac|1,3|whatever
aa:bb:cc:dd:ee:02|1,junk,6|bad options
aa:bb:cc:dd:ee:01|1,121,3,6,15,119,252|
aa:bb:cc:dd:ee:03||
aa:bb:cc:dd:ee:04|,|forged pretend line with | pipes
";
        let map = parse_fingerprint_lines(content);
        // Last event for :01 wins; MAC canonicalized to uppercase.
        assert_eq!(
            map.get("AA:BB:CC:DD:EE:01"),
            Some(&fp("1,121,3,6,15,119,252", ""))
        );
        // Bad MAC and bad options dropped; both-empty dropped.
        assert!(!map.contains_key("AA:BB:CC:DD:EE:02"));
        assert!(!map.contains_key("AA:BB:CC:DD:EE:03"));
        // Pipes in the vendor class stay in the vendor class.
        assert_eq!(
            map.get("AA:BB:CC:DD:EE:04"),
            Some(&fp(",", "forged pretend line with | pipes"))
        );
        assert_eq!(map.len(), 2);
    }

    #[test]
    fn label_format() {
        assert_eq!(
            device_label("B8:27:EB:12:34:AB", None).as_deref(),
            Some("Raspberry Pi Foundation device (1234ab)")
        );
        assert_eq!(device_label("DA:27:EB:12:34:56", None), None);
    }

    #[tokio::test]
    async fn ensure_uci_dhcpscript_sets_all_instances_and_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        tokio::fs::write(
            dir.path().join("dhcp"),
            "\
config dnsmasq
	option domainneeded '1'
	option localise_queries '1'

config dnsmasq 'dns_profile_guest'
	option noresolv '1'
	list server '127.0.0.1#10530'

config host 'host_nas'
	option mac 'AA:BB:CC:DD:EE:01'
	option name 'nas'
",
        )
        .await
        .unwrap();

        assert!(ensure_uci_dhcpscript(dir.path()).await.unwrap());
        let content = tokio::fs::read_to_string(dir.path().join("dhcp"))
            .await
            .unwrap();
        assert_eq!(
            content
                .matches("option dhcpscript '/etc/startwrt/dhcp-fingerprint.sh'")
                .count(),
            2,
            "both dnsmasq sections get the hook:\n{content}"
        );
        // Untouched: other options and non-dnsmasq sections.
        assert!(content.contains("option domainneeded '1'"));
        assert!(content.contains("option name 'nas'"));

        // Second run: no-op.
        assert!(!ensure_uci_dhcpscript(dir.path()).await.unwrap());
    }
}
