.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-pinhole-set-enabled 1  "set-enabled " 
.SH NAME
start\-tunnel\-pinhole\-set\-enabled \- Enable or disable an IPv6 pinhole
.SH SYNOPSIS
\fBstart\-tunnel pinhole set\-enabled\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIGUA\fR> <\fIEXTERNAL_PORT\fR> 
.SH DESCRIPTION
Enable or disable an IPv6 pinhole
.SH OPTIONS
.TP
\fB\-\-enabled\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGUA\fR>

.TP
<\fIEXTERNAL_PORT\fR>

