.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-pinhole-update-label 1  "update-label " 
.SH NAME
start\-tunnel\-pinhole\-update\-label \- Update the label of an IPv6 pinhole
.SH SYNOPSIS
\fBstart\-tunnel pinhole update\-label\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGUA\fR> <\fIEXTERNAL_PORT\fR> [\fILABEL\fR] 
.SH DESCRIPTION
Update the label of an IPv6 pinhole
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGUA\fR>

.TP
<\fIEXTERNAL_PORT\fR>

.TP
[\fILABEL\fR]

