[book]
authors = ["Start9"]
language = "en"
src = "src"
title = "Service Packaging"

[build]
build-dir = "book"

[preprocessor.tabs]

[output]

[output.html]
additional-css = ["./theme/youtube.css", "./theme/tabs.css", "./accent.css"]
additional-js = [
  "./theme/youtube.js",
  "./theme/tabs.js",
  "./theme/home-link.js",
]
admonitions = true
default-theme = "ayu"
edit-url-template = "https://github.com/Start9Labs/start-technologies/edit/master/projects/start-sdk/docs/{path}"
git-repository-url = "https://github.com/Start9Labs/start-technologies"
no-section-label = false
preferred-dark-theme = "ayu"
sidebar-header-nav = true
site-url = "/packaging/"

[output.html.fold]
enable = true
level = 0
