// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionResultMember } from './ActionResultMember'

export type ActionResultValue =
  | {
      type: 'single'
      /**
       * The actual string value to display. The UI renders it as a single-line field —
       * multi-line text belongs in the result's `message`.
       */
      value: string
      /**
       * (optional) Whether or not to include a copy to clipboard icon to copy the value
       */
      copyable?: boolean
      /**
       * (optional) Whether or not to also display the value as a QR code
       */
      qr?: boolean
      /**
       * (optional) Whether or not to mask the value using ●●●●●●●, which is useful for password or other sensitive information
       */
      masked?: boolean
      /**
       * (optional) Whether or not to include an open in new tab icon to launch the value, which must be an http(s) URL
       */
      launchable?: boolean
    }
  | {
      type: 'group'
      /**
       * An new group of nested values, experienced by the user as an accordion dropdown
       */
      value: Array<ActionResultMember>
    }
