// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckChallengeRes } from './CheckChallengeRes'
import type { CheckPortRes } from './CheckPortRes'
import type { CheckPortV6Res } from './CheckPortV6Res'
import type { QueryDnsRes } from './QueryDnsRes'

export type AddPublicDomainRes = {
  dns: QueryDnsRes
  port: CheckPortRes
  portV6: CheckPortV6Res | null
  /**
   * The authority's own reachability requirement, where the domain has one.
   */
  challenge: CheckChallengeRes | null
}
