// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaybeUtf8String } from './MaybeUtf8String'

/**
 * The protocols a binding answers with, carried on the wire as the list itself.
 */
export type AlpnInfo = Array<MaybeUtf8String>
