// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPortRes } from './CheckPortRes'
import type { CheckPortV6Res } from './CheckPortV6Res'

/**
 * Reachability of the port a certificate authority validates on. A null leg
 * went unprobed.
 */
export type CheckChallengeRes = {
  port: CheckPortRes | null
  portV6: CheckPortV6Res | null
}
