// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartOsRecoveryInfo } from './StartOsRecoveryInfo'

export type CifsBackupTarget = {
  hostname: string
  path: string
  username: string
  mountable: boolean
  available: number | null
  startOs: { [key: string]: StartOsRecoveryInfo }
  legacyBackup: boolean
}
