// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostnameInfo } from './HostnameInfo'

export type DerivedAddressInfo = {
  /**
   * User override: enable these addresses (only for public IP & port)
   */
  enabled: Array<string>
  /**
   * User override: disable these addresses (only for domains and private IP & port)
   */
  disabled: Array<[string, number]>
  /**
   * User override: IPv6 global-unicast addresses opted into WAN exposure.
   * Projected into `HostnameInfo.public` by `update_addresses`, so `public`
   * stays the single source of truth for WAN reachability (P2P address
   * selection, upstream pinholes). A GUA not in this set is LAN-only.
   */
  guaWan: Array<string>
  /**
   * COMPUTED: NetServiceData::update — all possible addresses for this binding
   */
  available: Array<HostnameInfo>
}
