// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from './ActionId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type EffectsRunActionParams = {
  packageId?: PackageId
  /**
   * The `eventId` from the `get-input` whose form this input answers.
   */
  eventId?: Guid
  actionId: ActionId
  input: any
}
