// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects how aggressively an EPP-capable CPU pursues performance.
 */
export type Epp = string
