// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from './DataUrl'

/**
 * A registry Start9 lists, and the identity it is expected to present.
 */
export type KnownRegistry = { url: string; name: string; icon: DataUrl | null }
