// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from './HostId'
import type { PackageId } from './PackageId'

export type PluginHostnameInfo = {
  /**
   * [`PackageId::start_os`] identifies the server's own host (the StartOS UI).
   */
  packageId: PackageId
  hostId: HostId
  internalPort: number
  ssl: boolean
  public: boolean
  hostname: string
  port: number | null
  info: unknown
}
